fix(CSS): Remove Figma Font Styles From CSS Output
Frontify/arcade-tokens pull request #63
Opened 2022-02-03 12:31 UTC by deniaz

2022-02-03 12:43 UTC, thisguyscode reviewed
@deniaz Figma output looks correct, so if you’re happy with the other outputs I’m happy to merge

2022-02-04 06:55 UTC, jonasbuechel reviewed
Compared the css output of all.css, we also dropped all these variables. Are all of them expected to be not generated?

--body-family-stack: Space Grotesk Frontify,Arial,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
  --body-size-x-small: 0.75rem;
  --body-size-small: 0.813rem;
  --body-size-medium: 0.875rem;
  --body-size-large: 1rem;
  --code-family-stack: Menlo,Courier,monospace;
  --code-size-small: 0.813rem;
  --code-size-medium: 0.875rem;
  --code-size-large: 1rem;
  --heading-family-stack: Space Grotesk Frontify,Arial,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
  --heading-size-medium: 0.875rem;
  --heading-size-large: 1rem;
  --heading-size-x-large: 1.5rem;
  --line-width: 0.063rem;
  --line-width-large: 0.125rem;
  --radius: 0.25rem;
  --radius-small: 0.125rem;
  --radius-large: 0.5rem;
  --radius-x-large: 0.75rem;
  --shadow-matrix: 0.1875rem 0rem 0.625rem 0rem #080808;
  --shadow-offset-x: 0rem;
  --shadow-offset-y: 0.1875rem;
  --shadow-spread: 0rem;
  --shadow-blur: 0.625rem;
  --shadow-top-matrix: -0.625rem 0rem 0.625rem -0.3125rem #080808;
  --shadow-top-offset-x: 0rem;
  --shadow-top-offset-y: -0.625rem;
  --shadow-top-spread: -0.3125rem;
  --shadow-bottom-matrix: 0.625rem 0rem 0.625rem -0.3125rem #080808;
  --shadow-bottom-offset-x: 0rem;
  --shadow-bottom-offset-y: 0.625rem;
  --shadow-bottom-spread: -0.3125rem;
  --shadow-large-matrix: 1.5625rem 0rem 5rem 0rem #080808;
  --shadow-large-offset-x: 0rem;
  --shadow-large-offset-y: 1.5625rem;
  --shadow-large-spread: 0rem;
  --shadow-large-blur: 5rem;

2022-02-11 10:34 UTC, jonasbuechel requested changes
compared output looks better now, just some last occurencies left:

`  --shadow: [object Object];
  --shadow-top: [object Object];
  --shadow-bottom: [object Object];
  --shadow-big: [object Object];`

2022-02-22 13:18 UTC, jonasbuechel approved these changes

2022-02-22 13:19 UTC, merged